apiVersion: v1
kind: Pod

metadata:
  name: go-playground

spec:
  containers:
  - name: go-playground
    image: gcr.io/journey-service-load-test/go-playground:v1
  nodeSelector:
    cloud.google.com/gke-nodepool: go-playground
  tolerations:
  - key: "node-pool"
    operator: "Equal"
    value: "go-playground"
    effect: "NoSchedule"
